# Generated by Django 4.1.6 on 2023-03-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidade', models.CharField(max_length=15)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostoGrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qm', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Subunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=250)),
                ('nome_guerra', models.CharField(max_length=80)),
                ('data_nasc', models.DateField()),
                ('posto_grad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.postograd')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FO+', 'Positiva'), ('FO-', 'Negativa'), ('N', 'Neutra')], default='N', max_length=3)),
                ('relato_fato', models.TextField(max_length=300)),
                ('militar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.militar')),
            ],
        ),
        migrations.AddField(
            model_name='militar',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='militar',
            name='qualificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.qualificacao'),
        ),
        migrations.AddField(
            model_name='militar',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.secao'),
        ),
        migrations.AddField(
            model_name='militar',
            name='subunidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subunidade'),
        ),
        migrations.CreateModel(
            name='Filiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pai', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_mae', models.CharField(max_length=250)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logadouro', models.CharField(max_length=200)),
                ('complemento', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=80)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15)),
                ('titulo_eleitor', models.CharField(max_length=50)),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('cat_cnh', models.CharField(blank=True, max_length=1, null=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
    ]
